# Generated by Django 3.1.3 on 2020-11-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='shorten_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
